import type { Har } from "../types/har";

export const maximalEvidenceHar: Har = {
  _captureExtension: { marker: "top-level-extension-evidence" },
  log: {
    version: "1.2",
    creator: { name: "evidence-creator", version: "9.8.7", comment: "creator-comment-evidence" },
    browser: { name: "evidence-browser", version: "6.5.4", comment: "browser-comment-evidence" },
    pages: [{
      startedDateTime: "2026-07-22T12:00:00.000Z",
      id: "page-evidence-id",
      title: "page-title-evidence",
      pageTimings: { onContentLoad: 12.5, onLoad: 42.5, comment: "page-timing-comment-evidence" },
      comment: "page-comment-evidence",
    }],
    comment: "log-comment-evidence",
    _logExtension: "log-extension-evidence",
    entries: [{
      startedDateTime: "2026-07-22T12:00:01.000Z",
      time: 123.4,
      serverIPAddress: "203.0.113.10",
      connection: "connection-evidence",
      pageref: "page-evidence-id",
      comment: "entry-comment-evidence",
      request: {
        method: "POST",
        url: "https://evidence.example.test/path?duplicate=one&duplicate=two",
        httpVersion: "HTTP/2.0",
        headers: [
          { name: "Content-Type", value: "application/json" },
          { name: "X-Evidence", value: "request-header-evidence", comment: "request-header-comment-evidence" },
        ],
        cookies: [{ name: "request-cookie", value: "request-cookie-value", path: "/", comment: "request-cookie-comment-evidence" }],
        queryString: [
          { name: "duplicate", value: "one", comment: "query-comment-one" },
          { name: "duplicate", value: "two", comment: "query-comment-two" },
        ],
        postData: {
          mimeType: "application/json",
          text: '{ "raw" : true, "order": [2,1] }\n',
          params: [{ name: "upload", value: "parameter-value", fileName: "evidence.txt", contentType: "text/plain", comment: "parameter-comment-evidence" }],
          comment: "post-data-comment-evidence",
        },
        headersSize: 222,
        bodySize: 38,
        comment: "request-comment-evidence",
      },
      response: {
        status: 302,
        statusText: "Found",
        httpVersion: "HTTP/2.0",
        headers: [
          { name: "Set-Cookie", value: "session=secret; Path=/; HttpOnly; SameSite=Lax; Priority=High; Partitioned" },
          { name: "X-Evidence", value: "response-header-evidence", comment: "response-header-comment-evidence" },
        ],
        cookies: [{ name: "session", value: "secret", path: "/", httpOnly: true, comment: "response-cookie-comment-evidence" }],
        content: {
          size: 18,
          compression: 3,
          mimeType: "application/json",
          text: '{ "result" : true }',
          encoding: "identity-evidence",
          comment: "content-comment-evidence",
        },
        redirectURL: "https://redirect.example.test/next",
        headersSize: 333,
        bodySize: 21,
        comment: "response-comment-evidence",
      },
      cache: { beforeRequest: { expires: "2026-07-23T00:00:00Z" }, comment: "cache-comment-evidence" },
      timings: {
        blocked: 1,
        dns: 2,
        connect: 3,
        ssl: 4,
        send: 5,
        wait: 100,
        receive: 8.4,
        comment: "timing-comment-evidence",
      },
      _futureEntryExtension: { marker: "entry-extension-evidence" },
      _recorder: {
        schemaVersion: "1",
        traceId: "trace-evidence",
        exchangeId: "exchange-evidence",
        redirectIndex: 2,
        state: "failed",
        error: {
          phase: "response_body",
          type: "evidence.Error",
          message: "error-message-evidence",
          timeout: true,
          temporary: false,
          contextCanceled: false,
          contextDeadlineExceeded: true,
          cause: "error-cause-evidence",
          unwrapChain: ["unwrap-one-evidence", "unwrap-two-evidence"],
        },
        network: {
          dnsAddresses: ["203.0.113.10"],
          dnsCoalesced: true,
          network: "tcp",
          localAddress: "192.0.2.10:54321",
          remoteAddress: "203.0.113.10:443",
          ipVersion: "IPv4",
          connectionReused: false,
          wasIdle: true,
          idleTimeMs: 7.5,
          proxy: "http://proxy.example.test:8080",
          http2: true,
          putIdle: { returned: false, error: "put-idle-error-evidence" },
        },
        tls: {
          version: "TLS 1.3",
          cipherSuite: "TLS_AES_128_GCM_SHA256",
          negotiatedProtocol: "h2",
          serverName: "evidence.example.test",
          handshakeComplete: true,
          didResume: false,
          ocspStapled: true,
          sctCount: 2,
          verifiedChains: 1,
          peerCertificates: [{
            subject: "certificate-subject-evidence",
            issuer: "certificate-issuer-evidence",
            serialNumber: "serial-evidence",
            dnsNames: ["evidence.example.test"],
            ipAddresses: ["203.0.113.10"],
            notBefore: "2026-01-01T00:00:00Z",
            notAfter: "2027-01-01T00:00:00Z",
            publicKeyAlgorithm: "ECDSA",
            signatureAlgorithm: "ECDSA-SHA256",
            sha256Fingerprint: "fingerprint-evidence",
            rawDER: "UkFXLURFUi1FVklERU5DRQ==",
          }],
        },
        expect100: { waited: true, continueReceived: true, waitMs: 6.5 },
        informational: [{ status: 103, headers: [{ name: "Link", value: "informational-header-evidence" }] }],
        requestBody: { present: true, complete: true, capturedBytes: 38, totalBytes: 38, hash: "request-hash-evidence", hashAlgorithm: "sha256", store: "request-store-evidence" },
        responseBody: { present: true, complete: false, closedEarly: true, truncated: true, capturedBytes: 18, totalBytes: 21, hash: "response-hash-evidence", hashAlgorithm: "sha256", readError: "read-error-evidence", closeError: "close-error-evidence", store: "response-store-evidence" },
        requestTrailers: [{ name: "X-Request-Trailer", value: "request-trailer-evidence" }],
        responseTrailers: [{ name: "X-Response-Trailer", value: "response-trailer-evidence" }],
        requestTransferEncoding: ["chunked"],
        responseTransferEncoding: ["chunked"],
        trace: [{ name: "GotConn", time: "2026-07-22T12:00:01.001Z", detail: "trace-detail-evidence" }],
        redaction: { request: { url: 1, headers: 2, queryParameters: 3, cookies: 4 }, response: { headers: 5, cookies: 6 }, errors: 7, rawTrace: 8 },
        responseBodyDecoded: true,
      },
    }],
  },
};
