import type { Har } from "./types/har";

// A small but comprehensive sample matching what github.com/mgurevin/recorder
// emits: success with gzip-decoded JSON + TLS + trace, a redirect chain, a
// DNS failure, a TLS failure, a truncated body and an early-closed body.
export const sampleHar: Har = {
  log: {
    version: "1.2",
    creator: { name: "recorder", version: "0.1.0" },
    entries: [
      {
        startedDateTime: "2026-07-17T09:15:02.120Z",
        time: 184.6,
        request: {
          method: "GET",
          url: "https://api.example.com/v1/orders?limit=20&token=%5BREDACTED%5D",
          httpVersion: "HTTP/2.0",
          cookies: [{ name: "session", value: "[REDACTED]" }],
          headers: [
            { name: "Host", value: "api.example.com" },
            { name: "Accept", value: "application/json" },
            { name: "Accept-Encoding", value: "gzip" },
            { name: "Authorization", value: "[REDACTED]" },
            { name: "User-Agent", value: "Go-http-client/2.0" },
          ],
          queryString: [
            { name: "limit", value: "20" },
            { name: "token", value: "[REDACTED]" },
          ],
          headersSize: -1,
          bodySize: 0,
        },
        response: {
          status: 200,
          statusText: "OK",
          httpVersion: "HTTP/2.0",
          cookies: [],
          headers: [
            { name: "Content-Type", value: "application/json" },
            { name: "Set-Cookie", value: "[REDACTED]" },
          ],
          content: {
            size: 158,
            mimeType: "application/json",
            text: '{\n  "orders": [\n    {"id": 9871, "state": "shipped", "total": "129.90"},\n    {"id": 9872, "state": "pending", "total": "58.00"}\n  ],\n  "next": null\n}',
            _decoded: true,
          },
          redirectURL: "",
          headersSize: -1,
          bodySize: -1,
        },
        cache: {},
        timings: { blocked: 0.4, dns: 8.2, connect: 21.9, ssl: 34.7, send: 0.2, wait: 112.1, receive: 6.9 },
        serverIPAddress: "93.184.216.34",
        connection: "54211",
        _traceId: "6f1c9b2a77aa41d0",
        _exchangeId: "e4b0c1d2f3a45678",
        _state: "completed",
        _network: {
          dnsAddresses: ["93.184.216.34", "2606:2800:220:1::1"],
          dnsCoalesced: true,
          network: "tcp",
          localAddress: "192.168.1.20:54211",
          remoteAddress: "93.184.216.34:443",
          ipVersion: "ipv4",
          connectionReused: false,
          wasIdle: false,
          http2: true,
          putIdle: { returned: true },
        },
        _tls: {
          version: "TLS 1.3",
          cipherSuite: "TLS_AES_128_GCM_SHA256",
          negotiatedProtocol: "h2",
          serverName: "api.example.com",
          handshakeComplete: true,
          didResume: false,
          ocspStapled: true,
          sctCount: 2,
          verifiedChains: 1,
          peerCertificates: [
            {
              subject: "CN=api.example.com,O=Example Corp",
              issuer: "CN=Example Intermediate CA,O=Example Trust",
              serialNumber: "31337421337",
              dnsNames: ["api.example.com", "*.example.com"],
              notBefore: "2026-01-01T00:00:00Z",
              notAfter: "2027-01-01T00:00:00Z",
              publicKeyAlgorithm: "ECDSA",
              signatureAlgorithm: "ECDSA-SHA256",
              sha256Fingerprint: "9f2d6c1b3a4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4",
              rawDER: "MIIBszCCAVmgAwIBAgIQf0kZDn0EXAMPLEONLY==",
            },
            {
              subject: "CN=Example Intermediate CA,O=Example Trust",
              issuer: "CN=Example Root,O=Example Trust",
              serialNumber: "1002003004",
              notBefore: "2024-01-01T00:00:00Z",
              notAfter: "2030-01-01T00:00:00Z",
              publicKeyAlgorithm: "RSA",
              signatureAlgorithm: "SHA256-RSA",
              sha256Fingerprint: "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee",
            },
          ],
        },
        _expect100: { waited: true, continueReceived: true, waitMs: 3.4 },
        _informational: [
          {
            status: 103,
            headers: [{ name: "Link", value: "</static/app.css>; rel=preload; as=style" }],
          },
        ],
        _responseBody: {
          present: true,
          complete: true,
          capturedBytes: 158,
          totalBytes: 158,
          hash: "b1946ac92492d2347c6235b4d2611184b1946ac92492d2347c6235b4d2611184",
          hashAlgorithm: "sha256",
        },
        _redaction: {
          request: { url: 1, headers: 1, queryParameters: 1, cookies: 1 },
          response: {
            headers: 1,
            body: { kind: "builtin:json", outcome: "unchanged", replacements: 0 },
          },
        },
        _responseTransferEncoding: ["chunked"],
        _trace: [
          { name: "GetConn", time: "2026-07-17T09:15:02.120Z", detail: "api.example.com:443" },
          { name: "DNSStart", time: "2026-07-17T09:15:02.121Z", detail: "api.example.com" },
          { name: "DNSDone", time: "2026-07-17T09:15:02.129Z", detail: "coalesced" },
          { name: "ConnectStart", time: "2026-07-17T09:15:02.129Z", detail: "tcp 93.184.216.34:443" },
          { name: "ConnectDone", time: "2026-07-17T09:15:02.151Z", detail: "tcp 93.184.216.34:443" },
          { name: "TLSHandshakeStart", time: "2026-07-17T09:15:02.151Z" },
          { name: "TLSHandshakeDone", time: "2026-07-17T09:15:02.186Z", detail: "h2" },
          { name: "GotConn", time: "2026-07-17T09:15:02.186Z", detail: "93.184.216.34:443" },
          { name: "WroteHeaders", time: "2026-07-17T09:15:02.187Z" },
          { name: "WroteRequest", time: "2026-07-17T09:15:02.187Z" },
          { name: "Got1xxResponse", time: "2026-07-17T09:15:02.240Z", detail: "103" },
          { name: "GotFirstResponseByte", time: "2026-07-17T09:15:02.299Z" },
          { name: "PutIdleConn", time: "2026-07-17T09:15:02.305Z" },
        ],
      },
      {
        startedDateTime: "2026-07-17T09:15:03.000Z",
        time: 12.1,
        request: {
          method: "GET",
          url: "https://shop.example.com/old-catalog",
          httpVersion: "HTTP/1.1",
          cookies: [],
          headers: [{ name: "Host", value: "shop.example.com" }],
          queryString: [],
          headersSize: -1,
          bodySize: 0,
        },
        response: {
          status: 301,
          statusText: "Moved Permanently",
          httpVersion: "HTTP/1.1",
          cookies: [],
          headers: [{ name: "Location", value: "/catalog" }],
          content: { size: 41, mimeType: "text/html; charset=utf-8" },
          redirectURL: "/catalog",
          headersSize: -1,
          bodySize: 41,
        },
        cache: {},
        timings: { blocked: 0.2, dns: 3.1, connect: 5.4, ssl: -1, send: 0.1, wait: 3.0, receive: 0.3 },
        serverIPAddress: "203.0.113.7",
        connection: "54290",
        _traceId: "chain-42",
        _exchangeId: "a1a1a1a1a1a1a1a1",
        _redirectIndex: 0,
        _state: "closed_early",
        _responseBody: { present: true, complete: false, closedEarly: true, capturedBytes: 0, totalBytes: 0 },
      },
      {
        startedDateTime: "2026-07-17T09:15:03.015Z",
        time: 48.9,
        request: {
          method: "GET",
          url: "https://shop.example.com/catalog",
          httpVersion: "HTTP/1.1",
          cookies: [],
          headers: [{ name: "Host", value: "shop.example.com" }],
          queryString: [],
          headersSize: -1,
          bodySize: 0,
        },
        response: {
          status: 200,
          statusText: "OK",
          httpVersion: "HTTP/1.1",
          cookies: [],
          headers: [{ name: "Content-Type", value: "text/html; charset=utf-8" }],
          content: {
            size: 96,
            mimeType: "text/html; charset=utf-8",
            text: "<!doctype html><html><head><title>Catalog</title></head><body><h1>Catalog</h1></body></html>",
          },
          redirectURL: "",
          headersSize: -1,
          bodySize: 96,
        },
        cache: {},
        timings: { blocked: 0.1, dns: -1, connect: -1, ssl: -1, send: 0.1, wait: 45.2, receive: 3.2 },
        serverIPAddress: "203.0.113.7",
        connection: "54290",
        _traceId: "chain-42",
        _exchangeId: "b2b2b2b2b2b2b2b2",
        _redirectIndex: 1,
        _state: "completed",
        _network: {
          network: "tcp",
          remoteAddress: "203.0.113.7:443",
          ipVersion: "ipv4",
          connectionReused: true,
          wasIdle: true,
          idleTimeMs: 9.1,
          http2: false,
        },
        _responseBody: { present: true, complete: true, capturedBytes: 96, totalBytes: 96 },
      },
      {
        startedDateTime: "2026-07-17T09:15:04.400Z",
        time: 41.7,
        request: {
          method: "POST",
          url: "http://billing.internal.invalid/api/charge",
          httpVersion: "",
          cookies: [],
          headers: [
            { name: "Host", value: "billing.internal.invalid" },
            { name: "Content-Type", value: "application/json" },
          ],
          queryString: [],
          postData: { mimeType: "application/json", text: '{"amount": 1290, "password": "[REDACTED]"}' },
          headersSize: -1,
          bodySize: 42,
        },
        response: {
          status: 0,
          statusText: "",
          httpVersion: "",
          cookies: [],
          headers: [],
          content: { size: 0, mimeType: "x-unknown" },
          redirectURL: "",
          headersSize: -1,
          bodySize: -1,
        },
        cache: {},
        timings: { blocked: -1, dns: 41.2, connect: -1, ssl: -1, send: -1, wait: -1, receive: -1 },
        _traceId: "f00dfeedcafe0001",
        _exchangeId: "c3c3c3c3c3c3c3c3",
        _state: "failed",
        _error: {
          phase: "dns",
          type: "*net.DNSError",
          message: "lookup billing.internal.invalid: no such host",
          timeout: false,
          temporary: false,
          contextCanceled: false,
          contextDeadlineExceeded: false,
          unwrapChain: ["*url.Error", "*net.OpError", "*net.DNSError"],
        },
      },
      {
        startedDateTime: "2026-07-17T09:15:05.100Z",
        time: 92.4,
        request: {
          method: "GET",
          url: "https://selfsigned.example.net/health",
          httpVersion: "",
          cookies: [],
          headers: [{ name: "Host", value: "selfsigned.example.net" }],
          queryString: [],
          headersSize: -1,
          bodySize: 0,
        },
        response: {
          status: 0,
          statusText: "",
          httpVersion: "",
          cookies: [],
          headers: [],
          content: { size: 0, mimeType: "x-unknown" },
          redirectURL: "",
          headersSize: -1,
          bodySize: -1,
        },
        cache: {},
        timings: { blocked: 0.3, dns: 6.0, connect: 12.6, ssl: -1, send: -1, wait: -1, receive: -1 },
        _traceId: "f00dfeedcafe0002",
        _exchangeId: "d4d4d4d4d4d4d4d4",
        _state: "failed",
        _error: {
          phase: "tls",
          type: "x509.UnknownAuthorityError",
          message: "tls: failed to verify certificate: x509: certificate signed by unknown authority",
          timeout: false,
          temporary: false,
          contextCanceled: false,
          contextDeadlineExceeded: false,
          unwrapChain: ["*url.Error", "*tls.CertificateVerificationError", "x509.UnknownAuthorityError"],
        },
        _network: {
          dnsAddresses: ["198.51.100.9"],
          network: "tcp",
          remoteAddress: "198.51.100.9:443",
          ipVersion: "ipv4",
          connectionReused: false,
          wasIdle: false,
          http2: false,
        },
      },
      {
        startedDateTime: "2026-07-17T09:15:06.250Z",
        time: 3410.8,
        request: {
          method: "GET",
          url: "https://cdn.example.com/exports/large-report.bin",
          httpVersion: "HTTP/2.0",
          cookies: [],
          headers: [{ name: "Host", value: "cdn.example.com" }],
          queryString: [],
          headersSize: -1,
          bodySize: 0,
        },
        response: {
          status: 200,
          statusText: "OK",
          httpVersion: "HTTP/2.0",
          cookies: [],
          headers: [{ name: "Content-Type", value: "application/octet-stream" }],
          content: {
            size: 9834127,
            mimeType: "application/octet-stream",
            text: "TWFnaWMgYnl0ZXMgZnJvbSBhIHRydW5jYXRlZCBjYXB0dXJlLi4u",
            encoding: "base64",
          },
          redirectURL: "",
          headersSize: -1,
          bodySize: 9834127,
        },
        cache: {},
        timings: { blocked: 0.2, dns: -1, connect: -1, ssl: -1, send: 0.1, wait: 88.9, receive: 3321.4 },
        serverIPAddress: "93.184.216.34",
        connection: "54211",
        _traceId: "0ddba11c0ffee003",
        _exchangeId: "e5e5e5e5e5e5e5e5",
        _state: "completed",
        _network: {
          network: "tcp",
          remoteAddress: "93.184.216.34:443",
          ipVersion: "ipv4",
          connectionReused: true,
          wasIdle: true,
          idleTimeMs: 812.4,
          http2: true,
        },
        _responseBody: {
          present: true,
          complete: true,
          truncated: true,
          capturedBytes: 1048576,
          totalBytes: 9834127,
          hash: "40af185bc356a4a5c2fe36d92bfd77dd6f47c1863502ee1e9741239ee5d55820",
          hashAlgorithm: "sha256",
        },
      },
    ],
  },
};
